apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "springboot"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: springboot-service
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: eksdemo
  sessionAffinity: None
  type: {{ .Values.service.type }}
